# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: tfq21
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: shrnk
# "service" is the name of this project. This will also be added to your AWS resource names.
service: shrnk

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    MONGO_URI: ${env:MONGO_URI}

functions:
  api:
    handler: dist/handler.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
  - serverless-plugin-typescript

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-users
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    URLsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-urls
        AttributeDefinitions:
          - AttributeName: shortID
            AttributeType: S
        KeySchema:
          - AttributeName: shortID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
