# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: tfq21
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: shrnk
# "service" is the name of this project. This will also be added to your AWS resource names.
service: shrnk

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    JWT_SECRET: ${env:JWT_SECRET}
    USERS_TABLE: ${self:service}-users
    URLS_TABLE: ${self:service}-urls
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
            - cloudformation:*
          Resource: "*"
functions:
  api:
    handler: dist/handler.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline

package:
  include:
    - views/** 
resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-users
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    URLsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-urls
        AttributeDefinitions:
          - AttributeName: shortID
            AttributeType: S
          - AttributeName: userId
            AttributeType: S  # needed for GSI
        KeySchema:
          - AttributeName: shortID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: userId-index
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
